### ISSUE TITLE
TypeScript compilation problem with angular 5.0.5

### ISSUE THREAD

**Issue by toregua** [Nightapes/HumanizeDuration.ts#5]
Hi and thanks for your plugin ;)

I met a problem when i want to "ng serve" my app since i upgrated to angular 5.0.5 : 
```

ERROR in ./node_modules/humanize-duration-ts/humanize-duration-ts.ts
Module build failed: Error: C:\ProjetsGIT\perso\SortieSportGit\SortieSportProfessionnel\node_modules\humanize-duration-ts\humanize-duration-ts.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\ProjetsGIT\perso\SortieSportGit\SortieSportProfessionnel\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:653:23)
    at plugin.done.then (C:\ProjetsGIT\perso\SortieSportGit\SortieSportProfessionnel\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/sortiesport/pages/sortie/sortie-form/sortie-form.page.ts 26:29-81
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts 
```

**Comment by canerelci** [comment]
Anybody out there to fix this?

**Comment by Nightapes** [comment]
I'm updating the library at the moment. A new version should be released soon.

**Comment by Nightapes** [comment]
@toregua @canerelci Please try version `2.0.0`
